### ISSUE TITLE
运行时出现Process finished with exit code 2

### ISSUE THREAD

**Issue by Wisdom-Lee-1224** [SO-JNU/stuhealth#1]

**Comment by IceYip** [comment]
请具体描述问题

**Comment by Wisdom-Lee-1224** [comment]
> 

![截图_20224829094806](https://user-images.githubusercontent.com/76644750/151663486-2d097df5-53d5-4e29-b840-de5f97d7e72c.png)
在使用GitHub action运行时出现此错误提示。

**Comment by IceYip** [comment]
请指定-ve参数
